# Generated by Django 4.2 on 2023-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=10, verbose_name='Цена')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография')),
                ('exist', models.BooleanField(default=True, verbose_name='Есть в наличии?')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебели',
                'ordering': ('name',),
            },
        ),
    ]
