# Generated by Django 4.2 on 2023-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ('name',), 'verbose_name': 'Мебель', 'verbose_name_plural': 'Мебель'},
        ),
        migrations.AlterField(
            model_name='furniture',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Фотография'),
        ),
    ]
