# Generated by Django 4.2 on 2023-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_furniture_options_alter_furniture_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фотография'),
        ),
    ]
