# Generated by Django 4.2 on 2023-05-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_alter_furniture_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('firstname', models.CharField(max_length=100, verbose_name='Фамилия сотрудника')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество сотрудника')),
                ('date_hired', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения договора')),
                ('position', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('exist', models.BooleanField(default=True, verbose_name='Числится в штате?')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название поставщика')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Имя агента поставщика')),
                ('agent_firstname', models.CharField(max_length=100, verbose_name='Фамилия агента поставщика')),
                ('agent_patronymic', models.CharField(max_length=100, verbose_name='Отчество агента поставщика')),
                ('exist', models.BooleanField(default=True, verbose_name='Сотрудничаем?')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('price', models.FloatField(null=True, verbose_name='Стоимость заказа')),
                ('address_delivery', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('1', 'Создан'), ('2', 'Отменён'), ('3', 'Согласован'), ('4', 'В пути'), ('5', 'Завершён')], max_length=150, verbose_name='Статус')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.employee', verbose_name='Сотрудник')),
                ('furniture', models.ManyToManyField(to='furniture.furniture')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_create'],
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.supplier', verbose_name='Поставщик'),
        ),
    ]
